services:
  backend:
    image: myapp:latest
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    networks:
      - mynetwork
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myphpadmin
    volumes:
      - mysql_data:/src/infrastructure/mysql
  volumes:
    mysql_data: